#spring.application.name=01_CustomerService
#spring.datasource.username=root
#spring.datasource.password=root123
#spring.datasource.url=jdbc:mysql://localhost:3306/customer_db
#spring.datasource.tomcat.driver-class-name=com.mysql.cj.jdbc.Driver
#
#logging.file.name=logs/customers.log
#
#springdoc.swagger-ui.enabled=false

spring:
    application:
        #name: "01_CustomerService"
       name: "CustomerService"      #To use the Eureka we need to remove number from the start of the application name
    datasource:
        username: root
        password: root123
        url: jdbc:mysql://localhost:3306/customer_db
        driver-class-name: com.mysql.cj.jdbc.Driver

    config: 
     import: "optional:configserver:http://localhost:8083/"    #Here is the path of actuator running server -- http://localhost:8083/actuator

    profiles:
      active:
       - "prod"

springdoc:
    api-docs:
        enabled: false

management:
  endpoints:
    web:
      exposure:
        include: "*"

logging:
    file:
        name: logs/customers.log

#Eureka Client confifuration
eureka:
  instance:
    prefer-ip-address: true	
  client:
    fetch-registry: true
    register-with-eureka: true	 
    service-url:
      defaultZone: http://localhost:8070/eureka     #here name should be from the git file "http://localhost:8083/eureka-server/default"


#Custom Properties - Used in application
build:
    version: "2.0"
customer:
    message: "Welcome to MSEDCL bank customer related REST API"
    contactDetails:
        name: "ISHWAR"
        email: "ishwar_chaudhari@mahadiscom.in"
    onCallSupport:
        - 1234567890
        - 9876543210
